name: treble
description: "Satya Ananda's music streaming app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.15
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  audio_video_progress_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/default_cover.png
    - assets/images/gene_parade.jpg
    - assets/images/satya.png
